name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and build
        working-directory: angular_CI-CD
        run: |
          cd angular_CI-CD
          npm install
          npm run gh-build
          cp dist/resource_web/index.html .

      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: . # The folder the action should deploy.  
